# Generated by Django 3.2.9 on 2021-11-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50)),
                ('user_email', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=50)),
                ('role', models.IntegerField(default=0)),
                ('company_name', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=500)),
                ('city_name', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
